package com.skillsurge.models

data class Comment(
   val commentId: String = "", // Auto-generated by Firestore
   val postId: String = "", // ID of the post being commented on
   val userId: String = "", // ID of the user who commented
   val content: String = "", // Comment content
   val timestamp: Long = System.currentTimeMillis() // Timestamp for comment
)