package com.skillsurge.models

data class Course(
    val id: String = "", // Auto-generated by Firestore
    val title: String = "",
    val description: String = "",
    val price: Double = 0.0,
    val instructorId: String = "", // ID of the instructor creating the course
    val createdAt: Long = System.currentTimeMillis() // Timestamp for course creation
)