package com.skillsurge.models

data class Like(
    val likeId: String = "", // Auto-generated by Firestore
    val postId: String = "", // ID of the post being liked
    val userId: String = "" // ID of the user who liked the post
)