package com.skillsurge.models

data class Message(
    val id: String = "", // Auto-generated by Firestore
    val senderId: String = "", // ID of the sender
    val receiverId: String = "", // ID of the receiver
    val text: String = "", // Message content
    val timestamp: Long = System.currentTimeMillis() // Timestamp for message
)